---
language: go
sudo: required

env:
  - K8S_VERSION=1.15.3 HELM_VERSION=2.14.3 NUM_NODES=3 PATH="/tmp/linux-amd64:$PATH"
  - K8S_VERSION=1.11.10 HELM_VERSION=2.14.3 NUM_NODES=3 PATH="/tmp/linux-amd64:$PATH"

install:
  - tests/k8s-euft/helm.sh local_install || exit 1
  - bats tests/k8s-euft/helm_lint.bats || exit 1
  - tests/k8s-euft/bootstrap_k8s.sh || exit 1
  - tests/k8s-euft/helm.sh install || exit 1

script:
  - tests/run_tests.sh
